# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/glacier/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/glacier/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so

# All the blobs necessary for glacier
PRODUCT_COPY_FILES += \
    vendor/htc/glacier/proprietary/akmd:/system/bin/akmd \
    vendor/htc/glacier/proprietary/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/glacier/proprietary/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/glacier/proprietary/logcat2:/system/bin/logcat2 \
    vendor/htc/glacier/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/glacier/proprietary/AudioBTID.csv:/system/etc/AudioBTID.csv \
    vendor/htc/glacier/proprietary/A1026_CFG.csv:/system/etc/A1026_CFG.csv \
    vendor/htc/glacier/proprietary/AdieHWCodec.csv:/system/etc/AdieHWCodec.csv \
    vendor/htc/glacier/proprietary/AdieHWCodec_WA.csv:/system/etc/AdieHWCodec_WA.csv \
    vendor/htc/glacier/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/glacier/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/glacier/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/glacier/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/glacier/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/glacier/proprietary/libGLESv2S3D_adreno200.so:/system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/htc/glacier/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/glacier/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/htc/glacier/proprietary/libC2D2.so:/system/lib/libC2D2.so \
    vendor/htc/glacier/proprietary/libc2d2_z180.so:/system/lib/libc2d2_z180.so \
    vendor/htc/glacier/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/glacier/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/glacier/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/glacier/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/glacier/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/glacier/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/glacier/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/glacier/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/glacier/proprietary/camera.default.so:/system/lib/hw/camera.default.so \
    vendor/htc/glacier/proprietary/libOlaEngine.so:/system/lib/libOlaEngine.so \
    vendor/htc/glacier/proprietary/libcameraface.so:/system/lib/libcameraface.so \
    vendor/htc/glacier/proprietary/libcamerapp.so:/system/lib/libcamerapp.so \
    vendor/htc/glacier/proprietary/libchromatix_s5k4e1gx_default_video.so:/system/lib/libchromatix_s5k4e1gx_default_video.so \
    vendor/htc/glacier/proprietary/libchromatix_s5k4e1gx_preview.so:/system/lib/libchromatix_s5k4e1gx_preview.so \
    vendor/htc/glacier/proprietary/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/htc/glacier/proprietary/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/htc/glacier/proprietary/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/htc/glacier/proprietary/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/htc/glacier/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/htc/glacier/proprietary/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/htc/glacier/proprietary/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/htc/glacier/proprietary/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/htc/glacier/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/htc/glacier/proprietary/libwvm.so:/system/lib/libwvm.so \
    vendor/htc/glacier/proprietary/libWVStreamControlAPI_L3.so:/system/lib/libWVStreamControlAPI_L3.so \
    vendor/htc/glacier/proprietary/libdrmwvmplugin.so:/system/lib/drm/libdrmwvmplugin.so \
    vendor/htc/glacier/proprietary/libwvdrm_L3.so:/system/lib/libwvdrm_L3.so \
    vendor/htc/glacier/proprietary/libv8.so:/system/lib/libv8.so \
    vendor/htc/glacier/proprietary/libv8.so:obj/lib/libv8.so \
    vendor/htc/glacier/proprietary/libpatts_engine_jni_api.so:/system/lib/libpatts_engine_jni_api.so \
    vendor/htc/glacier/proprietary/libttscompat.so:/system/lib/libttscompat.so
